### ISSUE TITLE
Can't scroll

### ISSUE THREAD

**Issue by girasquid** [ExchangeJS/june-2015-notes#1]
I loaded the notes page at http://www.exchangejs.com/june-2015-notes/#/ but it looks like it's only a single page - I tried moving my mouse around, clicking, and scrolling and I can't seem to get past the first page. I can see in index.html that there are more notes ON the page - how do I get at them?

**Comment by JeffMarvin** [comment]
Use your arrow keys. The index.html is in a presentation format using reveal.js.

**Comment by girasquid** [comment]
Cool, thanks.

**Comment by MarkBennett** [comment]
We used to have a little arrow pad you could click on in the corner to help navigate as well. We removed it as it was getting in the way most of the time. If we here this starts to become a common issue, will look at bringing them back. Thanks for making an issue. Feedback is always good to get!
